spring:
  datasource:
    url: jdbc:mysql://mysqldb/bootdb
    username: root
    password: root
  application:
    name: CRUD-OP
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000


