spring:
  datasource:
#    url: jdbc:mysql://mysqldb/bootdb
    url: jdbc:mysql://${SERVERM}/rakuten
#    username: roshan
#    password: Qwert1@
    username: ${USER}
    password: ${PASS}
  application:
    name: CRUD-OP
  jpa:
    generate-ddl: true
    
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8000



