spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rakuten
    username: roshan
    password: Qwert1@
  application:
    name: CRUD-OP
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000


